## Week 2 In-class Activity

In [8]:
import numpy as np

1. Create an array with your team members birthdays such that each team member is a row with the month in the first spot, date in the second spot, last two year digits in the third spot. For example, a birthday of November 15 1986 would look like [11,15,86]. Take the square root of this array.

In [10]:
a = [[9,16,82],[3,5,22],[11,4,10],[6,25,11]]
print(a)
np.sqrt(a)

[[9, 16, 82], [3, 5, 22], [11, 4, 10], [6, 25, 11]]


array([[3.        , 4.        , 9.05538514],
       [1.73205081, 2.23606798, 4.69041576],
       [3.31662479, 2.        , 3.16227766],
       [2.44948974, 5.        , 3.31662479]])

2. Create a second arry with your each team members lucky number, number of pets, number of siblings. For example, my lucky number is 14, I have 2 pets, and 1 sibling so my row would be [14,2,1]. Find the mean of the new array.

In [12]:
b = [[4,2,6],[2,5,9],[6,7,9],[10,7,25]]
np.mean(b)

7.666666666666667

3. Add your arrays from step 1 and step 2. Then subtract step 2 from step 1. 

In [14]:
added_array = np.add(a,b)
print(added_array)

[[13 18 88]
 [ 5 10 31]
 [17 11 19]
 [16 32 36]]


In [15]:
subtracted_array = np.subtract(a,b)
print(subtracted_array)

[[  5  14  76]
 [  1   0  13]
 [  5  -3   1]
 [ -4  18 -14]]


4.  Transpose your array from step two and find the average lucky number, number of pets, and number of sibling of your team members in one step.

In [19]:
##https://panjeh.medium.com/how-to-get-average-of-rows-columns-in-a-numpy-array-8f305dd92624
t= np.transpose(b)
print(t)
np.mean(t, axis =1)

[[ 4  2  6 10]
 [ 2  5  7  7]
 [ 6  9  9 25]]


array([ 5.5 ,  5.25, 12.25])

5. Concatenate your arrays from step 1 and step 2 so that each row represents data from a single team member. 

In [21]:
c= np.concatenate((a,b),axis=1)
print(c)

[[ 9 16 82  4  2  6]
 [ 3  5 22  2  5  9]
 [11  4 10  6  7  9]
 [ 6 25 11 10  7 25]]


6. Jimmy and Delilah are my dogs. One day, my boyfriend and I were bored and decided to see how many piece of popcorn each dog could catch. Over the next 10 days, we would toss them 10 pieces a day and keep track of whether they caught them or not (caught=1, did not catch=0) PLEASE NOTE: no dogs were harmed during this experiment.

Read in the dogs.xlsx data set. We always tossed to Jimmy first than Delilah. Each column is a toss. 

In [22]:
import pandas as pd

In [31]:
dogs=pd.read_csv(r"C:\Users\Linet Nabwire\Desktop\PyStat\Programing for analytics\Dogs.csv",header=None)
print(dogs)

    0  1  2  3  4  5  6  7  8  9
0   0  0  1  0  1  0  0  0  1  0
1   0  1  1  1  1  1  0  0  1  0
2   0  0  0  1  1  1  0  0  0  0
3   0  1  0  0  0  0  1  1  0  1
4   0  0  0  1  1  1  0  0  1  1
5   0  0  0  1  0  0  1  1  0  0
6   1  0  1  0  1  0  0  0  0  1
7   1  0  0  0  0  0  0  0  0  0
8   0  1  1  0  0  1  1  1  0  1
9   1  1  1  1  1  0  1  0  1  1
10  1  1  0  0  1  0  0  1  1  1
11  1  1  1  1  0  1  1  0  1  1
12  1  0  1  0  0  0  1  1  0  1
13  0  0  0  1  1  1  1  1  0  0
14  0  1  1  1  1  0  1  1  1  1
15  1  0  0  0  0  1  1  0  0  1
16  1  0  1  0  1  0  1  1  0  1
17  0  0  1  0  0  1  0  1  1  1
18  0  0  1  1  0  0  0  0  1  1
19  1  0  1  0  0  0  1  0  0  1


7. Reindex with the dogs names on the appropriate rows and the toss number as the column name.

In [37]:
dogs.columns=['Toss1','Toss2','Toss3','Toss4','Toss5','Toss6','Toss7','Toss8','Toss9','Toss10']
dogs.index =(['Jimmy','Delilah']*10)
print(dogs)

         Toss1  Toss2  Toss3  Toss4  Toss5  Toss6  Toss7  Toss8  Toss9  Toss10
Jimmy        0      0      1      0      1      0      0      0      1       0
Delilah      0      1      1      1      1      1      0      0      1       0
Jimmy        0      0      0      1      1      1      0      0      0       0
Delilah      0      1      0      0      0      0      1      1      0       1
Jimmy        0      0      0      1      1      1      0      0      1       1
Delilah      0      0      0      1      0      0      1      1      0       0
Jimmy        1      0      1      0      1      0      0      0      0       1
Delilah      1      0      0      0      0      0      0      0      0       0
Jimmy        0      1      1      0      0      1      1      1      0       1
Delilah      1      1      1      1      1      0      1      0      1       1
Jimmy        1      1      0      0      1      0      0      1      1       1
Delilah      1      1      1      1      0      1   

Answer the following questions using the dogs data set:

8. How many times did Delilah catch the popcorn on the 3rd toss?

In [42]:
sum(dogs['Toss3']['Delilah'])

5

9. Sum the number of catches for each day for Jimmy. Does it seems like Jimmy got better at catching popcorn over time? *NOTE: you do not have to do a statistical test, but you do need to justify why you think this may be the case.

In [47]:
toss_sum=dogs[dogs.index=='Jimmy'].sum()
toss_sum

Toss1     4
Toss2     3
Toss3     7
Toss4     4
Toss5     7
Toss6     3
Toss7     4
Toss8     5
Toss9     5
Toss10    8
dtype: int64

In [55]:
dogs.loc['Jimmy'].sum()

Toss1     4
Toss2     3
Toss3     7
Toss4     4
Toss5     7
Toss6     3
Toss7     4
Toss8     5
Toss9     5
Toss10    8
dtype: int64

10. Which dog caught more popcorn over all of the days?

In [52]:
totaljimmysum =toss_sum.sum()
totaljimmysum

50

In [53]:
dog2sum=(dogs[dogs.index=='Delilah'].sum()).sum()
dog2sum

48

In [51]:
if totraljimmysum>dog2sum:
    print('Jimmy')
else:
    print('dog2')

Jimmy
